[build-system]
requires = ["hatchling >= 1.27", "hatch-vcs >= 0.5"]
build-backend = "hatchling.build"

[project]
name = "tidal_fvcom"
version = "1.1.0"
description = "Processing pipeline for the DOE H2O high resolution tidal (FVCOM) hindcast"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["tidal_fvcom*"]

[tool.setuptools.package-data]
tidal_fvcom = ["references/*"]

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
ignore = ["F401"]
