#!/bin/bash
#SBATCH --account=hindcastra
#SBATCH --output=generate_manifest_%j.out
#SBATCH --job-name=generate_manifest
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=andrew.simms@nlr.gov
##SBATCH --time=8:00:00
##SBATCH --partition=shared
##SBATCH --mem=64G
#SBATCH --time=59:00
#SBATCH --partition=debug

# Prepare for python script execution
source hpc/sbatch_env_setup.sh

# Run the manifest generation script
python -m tidal_fvcom.steps.generate_parquet_partition_manifest_json
